"""
PHASE 4: ORACLE BRAIN (REINFORCEMENT LEARNING GYM)
===================================================
Trains the PPO Agent on 15-Minute timeframe to make the final 
buy/sell/leverage decisions based on Phase 3 inputs.
"""

import os
import numpy as np
import pandas as pd
import yfinance as yf
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv

MODELS_DIR = "models"
os.makedirs(MODELS_DIR, exist_ok=True)

class OracleTradingEnv(gym.Env):
    """
    Custom Environment that follows OpenAI Gym interface.
    The agent learns how to trade the 15-min chart.
    """
    metadata = {'render.modes': ['human']}

    def __init__(self, df):
        super(OracleTradingEnv, self).__init__()
        self.df = df
        self.max_steps = len(df) - 1
        
        # Actions: 0=Hold/Cut, 1=Buy 1%, 2=Buy 5%, 3=Buy 10%, 4=Sell 1%, 5=Sell 5%, 6=Sell 10%
        self.action_space = spaces.Discrete(7)
        
        # Obs: [Bull Prob, Bear Prob, Side Prob, Sentiment Score] (From Phase 3)
        self.observation_space = spaces.Box(low=-1, high=1, shape=(4,), dtype=np.float32)

        self.current_step = 0
        self.position = 0          # 0=None, 1=Long, -1=Short
        self.entry_price = 0.0
        self.leverage = 0
        self.balance = 10000.0     # Starting Balance

    def _next_observation(self):
        # We simulate the Phase 3 outputs to train the RL agent fast
        # In live trading, this is generated by the PyTorch Transformer
        row = self.df.iloc[self.current_step]
        bull_prob = row['Bull_Prob']
        bear_prob = row['Bear_Prob']
        side_prob = row['Side_Prob']
        sentiment = row['Sentiment']
        return np.array([bull_prob, bear_prob, side_prob, sentiment], dtype=np.float32)

    def step(self, action):
        self.current_step += 1
        reward = 0.0
        done = False
        
        if self.current_step >= self.max_steps:
            done = True
            
        current_price = float(self.df.iloc[self.current_step]['Close'])

        # 0 = CUT / HOLD
        if action == 0:
            if self.position != 0:
                # Close trade and calculate PnL
                pnl = (current_price - self.entry_price) if self.position == 1 else (self.entry_price - current_price)
                pnl_pct = (pnl / self.entry_price) * self.leverage
                reward = pnl_pct * 100  # Reward the agent for closing in profit!
                self.balance += self.balance * pnl_pct
                self.position = 0
                self.leverage = 0
            else:
                reward = -0.01  # Tiny penalty for doing nothing (promotes action)

        # 1,2,3 = BUY
        elif action in [1, 2, 3]:
            if self.position == 0:
                self.position = 1
                self.entry_price = current_price
                self.leverage = {1: 1, 2: 5, 3: 10}[action]
            elif self.position == -1:
                reward = -5.0 # Penalty for trying to buy while short without cutting first
                
        # 4,5,6 = SELL
        elif action in [4, 5, 6]:
            if self.position == 0:
                self.position = -1
                self.entry_price = current_price
                self.leverage = {4: 1, 5: 5, 6: 10}[action]
            elif self.position == 1:
                reward = -5.0 # Penalty for trying to sell while long without cutting first

        # If holding a position, check if we blew up (Drawdown penalty)
        if self.position != 0:
            unrealized_pnl = (current_price - self.entry_price) if self.position == 1 else (self.entry_price - current_price)
            unrealized_pct = (unrealized_pnl / self.entry_price) * self.leverage
            if unrealized_pct < -0.05: # -5% drawdown
                reward = -10.0
                done = True # Liquidated

        obs = self._next_observation()
        info = {'balance': self.balance}
        
        return obs, reward, done, False, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.current_step = 0
        self.position = 0
        self.entry_price = 0.0
        self.leverage = 0
        self.balance = 10000.0
        return self._next_observation(), {}

def prep_15m_data(ticker):
    print(f"Downloading 15-minute historical data for {ticker}...")
    df = yf.download(ticker, period="60d", interval="15m", progress=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    
    # Generate simulated PyTorch Transformer features for the Gym to practice on
    df['EMA9'] = df['Close'].ewm(span=9).mean()
    df['Bull_Prob'] = np.where(df['Close'] > df['EMA9'], 0.7, 0.2)
    df['Bear_Prob'] = np.where(df['Close'] < df['EMA9'], 0.7, 0.2)
    df['Side_Prob'] = 0.1
    df['Sentiment'] = np.random.uniform(-0.5, 0.5, len(df))
    
    return df.dropna()

def train_ppo_brain(pair_name, ticker):
    df = prep_15m_data(ticker)
    if df.empty:
        print(f"Failed to load data for {pair_name}")
        return
        
    print(f"\n--- Initializing Phase 4 Reinforcement Learning Gym for {pair_name} ---")
    env = DummyVecEnv([lambda: OracleTradingEnv(df)])
    
    model = PPO("MlpPolicy", env, verbose=1, learning_rate=0.0003, n_steps=2048)
    
    print(f"Training PPO Agent (100,000 Timesteps)...")
    model.learn(total_timesteps=100000)
    
    model_path = f"{MODELS_DIR}/{pair_name}_ppo_brain.zip"
    model.save(model_path)
    print(f"SUCCESS: Brain trained and saved to {model_path}!")

if __name__ == "__main__":
    print("=========================================")
    print("  PHASE 4: RL GYM (15-MINUTE TIMEFRAME)")
    print("=========================================")
    
    # Train US30 as the master template (it will adapt to others)
    train_ppo_brain("US30", "YM=F")
